project:
  type: website
  output-dir: "docs"
website:
  title: "Protfolio"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: Portfolio.qmd
    right:
      - text: "Contact"
        file: contact.qmd
      - text: "Learn"
        file: Blog.qmd
      - icon: github
        href: https://github.com/afaaqitc
format:
  html:
    theme: Lumen
    css: styles.css

editor: visual

